from Tkinter import *

DEFAULT_FONT=("Helvetica","12","bold")
CARD_FONT=("Helvetica","10","bold")
BARREL_FONT=("Helvetica","8","bold")
COMPANY_NAME_FONT=("Helvetica","16")

COMPANY_COLORS = [ "#b00", "#00b", "#0a0", "#505" ]
DEFAULT_NAMES = ( "AMERICO", "BOARDGAMECO","CONGLOMCO","DYNAMICO")
CARD_BACKGROUND="#bbf"
CARD_FOREGROUND="#000"
CARD_WIDTH=13
CARD_RELIEF=RIDGE
CARD_HIGHLIGHT="#ffb"
MENU_LABEL_WIDTH=12
TEXT_COLOR="white"

MESSAGE_LIST_HEIGHT=4
MESSAGE_LIST_WIDTH=120

SHOW_ALL_MONEY=1


#constants
CONTROL_HUMAN=1
CONTROL_AI=0
